"""
TO KNOW WHICH VERSION OF PYTHON YOU ARE USING
IN YOUR TERMINAL YOU CAN TYPE
"""
python --version

"""IF IT DOESN'T WORK YOU CAN STILL USE THE BELOW COMMAND TO KNOW THE VERSION"""
python3 --version

"""
YOU CAN EVEN DO THE SAME IN YOUR RUNTIME USING THE SYS BUILT IN MODULE
"""
import sys
print(sys.version_info)
print(sys.version)


#NOTE
"""
IT IS RECOMMENDED FOR YOU TO USE PYTHON 2
SINCE JANUARY 1,20 PYTHON 2 WILL NOT GET MAINTAINED 
"""
